tb = int(input('Digite um número para ver sua tabuada: '))
t1 = tb * 1
t2 = tb * 2
t3 = tb * 3
t4 = tb * 4
t5 = tb * 5
t6 = tb * 6
t7 = tb * 7
t8 = tb * 8
t9 = tb * 9
t10 = tb * 10
print('{} x 1 = {}'.format(tb, t1))
print('{} x 2 = {}'.format(tb, t2))
print('{} x 3 = {}'.format(tb, t3))
print('{} x 4 = {}'.format(tb, t4))
print('{} x 5 = {}'.format(tb, t5))
print('{} x 6 = {}'.format(tb, t6))
print('{} x 7 = {}'.format(tb, t7))
print('{} x 8 = {}'.format(tb, t8))
print('{} x 9 = {}'.format(tb, t9))
print('{} x 10 = {}'.format(tb, t10))
